[package]
name = "ulmensa"
version = "0.1.0"
edition = "2021"

[dependencies]
tl = "0.7.8"
reqwest = { version = "0.12", default-features=false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["full"] }
regex = "1.11.1"
prettytable = "0.10.0"
